const races = {
    "Dragonborn": {
        maxAge: 80,
        subraces: "",
        baseInches: 66,
        heightDiceType: 8,
        weightDiceRolls: 2,
        weightDiceType: 6,
        basePounds: 175,
        size: "Medium",
    },
    "Dwarf": {
        maxAge: 350,
        subraces: {
            "Hill Dwarf": {
                baseInches: 44,
                heightDiceType: 4,
                weightDiceRolls: 2,
                weightDiceType: 6,
                basePounds: 115,
                size: "Medium",
            },
            "Mountain Dwarf": {
                baseInches: 48,
                heightDiceType: 4,
                weightDiceRolls: 2,
                weightDiceType: 6,
                basePounds: 130,
                size: "Medium",
            },
        },
    },
    "Elf": {
        maxAge: 750,
        subraces: {
            "High Elf": {
                baseInches: 54,
                heightDiceType: 10,
                weightDiceRolls: 1,
                weightDiceType: 4,
                basePounds: 90,
                size: "Medium",
            },
            "Wood Elf": {
                baseInches: 54,
                heightDiceType: 10,
                weightDiceRolls: 1,
                weightDiceType: 4,
                basePounds: 100,
                size: "Medium",
            },
            "Dark Elf": {
                baseInches: 53,
                heightDiceType: 6,
                weightDiceRolls: 1,
                weightDiceType: 6,
                basePounds: 75,
                size: "Medium",
            },
        },
    },
    "Gnome": {
        maxAge: 499,
        subraces: {
            "Forest Gnome": {
                baseInches: 35,
                heightDiceValue: 4,
                weightDiceRolls: 1,
                weightDiceType: 1,
                basePounds: 35,
                size: "Small",
            },
            "Rock Gnome": {
                baseInches: 35,
                heightDiceValue: 4,
                weightDiceRolls: 1,
                weightDiceType: 1,
                basePounds: 35,
                size: "Small",
            },
        },

    },
    "Half-Elf": {
        maxAge: 200,
        subraces: "",
        baseInches: 57,
        heightDiceType: 8,
        weightDiceRolls: 2,
        weightDiceType: 4,
        basePounds: 110,
        size: "Medium",
    },
    "Halfling": {
        maxAge: 150,
        subraces: {
            "Lightfoot": {
                baseInches: 31,
                heightDiceValue: 4,
                weightDiceRolls: 1,
                weightDiceType: 1,
                basePounds: 35,
                size: "Small",
            },
            "Stout": {
                baseInches: 31,
                heightDiceValue: 4,
                weightDiceRolls: 1,
                weightDiceType: 1,
                basePounds: 35,
                size: "Small",
            },
        },

    },
    "Half-Orc": {
        maxAge: 75,
        subraces: "",
        baseInches: 58,
        heightDiceType: 10,
        weightDiceRolls: 2,
        weightDiceType: 6,
        basePounds: 140,
        size: "Medium",
    },
    "Human": {
        maxAge: 99,
        subraces: "",
        baseInches: 56,
        heightDiceType: 10,
        weightDiceRolls: 2,
        weightDiceType: 4,
        basePounds: 110,
        size: "Medium",
    },
    "Tiefling": {
        maxAge: 110,
        subraces: "",
        baseInches: 57,
        heightDiceType: 8,
        weightDiceRolls: 2,
        weightDiceType: 4,
        basePounds: 110,
        size: "Medium",
    },
};