const races = {
    "Dragonborn": {
        maxAge: 80,
        subraces: "",
        baseInches: 66,
        heightDiceType: 8,
        weightDiceRolls: 2,
        weightDiceType: 6,
        basePounds: 175,
        size: "Medium",
        speed: 30,
        languages: ["Common", " Draconic"],
        extraLanguages: 0,
        darkVision: 0,
    },
    "Dwarf": {
        maxAge: 350,
        subraces: {
            "Hill Dwarf": {
                baseInches: 44,
                heightDiceType: 4,
                weightDiceRolls: 2,
                weightDiceType: 6,
                basePounds: 115,
                size: "Medium",
                speed: 25,
                languages: ["Common", " Dwarvish"],
                extraLanguages: 0,
                darkVision: 60,
            },
            "Mountain Dwarf": {
                baseInches: 48,
                heightDiceType: 4,
                weightDiceRolls: 2,
                weightDiceType: 6,
                basePounds: 130,
                size: "Medium",
                speed: 25,
                languages: ["Common", " Dwarvish"],
                extraLanguages: 0,
                darkVision: 60,
            },
        },
    },
    "Elf": {
        maxAge: 750,
        subraces: {
            "High Elf": {
                baseInches: 54,
                heightDiceType: 10,
                weightDiceRolls: 1,
                weightDiceType: 4,
                basePounds: 90,
                size: "Medium",
                speed: 30,
                languages: ["Common", " Elvish"],
                extraLanguages: 1,
                darkVision: 60,
            },
            "Wood Elf": {
                baseInches: 54,
                heightDiceType: 10,
                weightDiceRolls: 1,
                weightDiceType: 4,
                basePounds: 100,
                size: "Medium",
                speed: 35,
                languages: ["Common", " Elvish"],
                extraLanguages: 0,
                darkVision: 60,
            },
            "Dark Elf": {
                baseInches: 53,
                heightDiceType: 6,
                weightDiceRolls: 1,
                weightDiceType: 6,
                basePounds: 75,
                size: "Medium",
                speed: 30,
                languages: ["Common", " Elvish"],
                extraLanguages: 0,
                darkVision: 120,
            },
        },
    },
    "Gnome": {
        maxAge: 499,
        subraces: {
            "Forest Gnome": {
                baseInches: 35,
                heightDiceValue: 4,
                weightDiceRolls: 1,
                weightDiceType: 1,
                basePounds: 35,
                size: "Small",
                speed: 25,
                languages: ["Common", " Gnomish"],
                extraLanguages: 0,
                darkVision: 60,
            },
            "Rock Gnome": {
                baseInches: 35,
                heightDiceValue: 4,
                weightDiceRolls: 1,
                weightDiceType: 1,
                basePounds: 35,
                size: "Small",
                speed: 25,
                languages: ["Common", " Gnomish"],
                extraLanguages: 0,
                darkVision: 60,
            },
        },

    },
    "Half-Elf": {
        maxAge: 200,
        subraces: "",
        baseInches: 57,
        heightDiceType: 8,
        weightDiceRolls: 2,
        weightDiceType: 4,
        basePounds: 110,
        size: "Medium",
        speed: 30,
        languages: ["Common", " Elvish"],
        extraLanguages: 1,
        darkVision: 60,
    },
    "Halfling": {
        maxAge: 150,
        subraces: {
            "Lightfoot": {
                baseInches: 31,
                heightDiceValue: 4,
                weightDiceRolls: 1,
                weightDiceType: 1,
                basePounds: 35,
                size: "Small",
                speed: 25,
                languages: ["Common", " Halfling"],
                extraLanguages: 0,
                darkVision: 0,
            },
            "Stout": {
                baseInches: 31,
                heightDiceValue: 4,
                weightDiceRolls: 1,
                weightDiceType: 1,
                basePounds: 35,
                size: "Small",
                speed: 25,
                languages: ["Common", " Halfling"],
                extraLanguages: 0,
                darkVision: 0,
            },
        },

    },
    "Half-Orc": {
        maxAge: 75,
        subraces: "",
        baseInches: 58,
        heightDiceType: 10,
        weightDiceRolls: 2,
        weightDiceType: 6,
        basePounds: 140,
        size: "Medium",
        speed: 30,
        languages: ["Common", " Orc"],
        extraLanguages: 0,
        darkVision: 60,
    },
    "Human": {
        maxAge: 99,
        subraces: "",
        baseInches: 56,
        heightDiceType: 10,
        weightDiceRolls: 2,
        weightDiceType: 4,
        basePounds: 110,
        size: "Medium",
        speed: 30,
        languages: ["Common"],
        extraLanguages: 1,
        darkVision: 0,
    },
    "Tiefling": {
        maxAge: 110,
        subraces: "",
        baseInches: 57,
        heightDiceType: 8,
        weightDiceRolls: 2,
        weightDiceType: 4,
        basePounds: 110,
        size: "Medium",
        speed: 30,
        languages: ["Common", " Infernal"],
        extraLanguages: 0,
        darkVision: 60,
    },
};